// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  breadcrumbs: dynamic(() => import("./Breadcrumbs")),
  contact: dynamic(() => import("./Contact")),
  cta: dynamic(() => import("./Cta")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image_description_card_section: dynamic(
    () => import("./ImageDescriptionCardSection"),
  ),
  logo_carousel: dynamic(() => import("./LogoCarousel")),
  paginated_items: dynamic(() => import("./PaginatedItems")),
  questions: dynamic(() => import("./Questions")),
  statistics: dynamic(() => import("./Statistics")),
  testimonial: dynamic(() => import("./Testimonial")),
};
